services:
  - type: web
    name: mon-superviseur-ia
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=$PYTHONPATH:/opt/render/project/src streamlit run app/interface/main.py
    envVars:
      - key: CLAUDE_API_KEY
        sync: false